baseURL = 'https://rikiso.github.io/'
languageCode = 'ja-jp'
title = '理基礎教'
theme = "paper"

[params]
  color = 'linen'

  github = 'rikiso/rikiso.github.io'
  rss = true

  monoDarkIcon = true

[menu]

  [[menu.main]]
    identifier = "disclaimer"
    name = "免責事項"
    url = "/disclaimer/"
    weight = 10
